### ISSUE TITLE
Duplicating an event in week view goes to day view.

### ISSUE THREAD

**Issue by navaneethnpk** [fabiosangregorio/google-calendar-quick-duplicate#18] opened 2023-04-26 12:33 UTC
My default google calender view is "Week View". Now whenever I duplicate an event using the extension, my calender view will become "Day view" I have to got back to week view. 

--------------------------------------------------------------------
Version: 1.1.0
Browser: Chrome (Version 112.0.5615.165)
OS: Ubuntu 23.04

**Comment by fabiosangregorio** [comment] 2023-12-04 09:14
Duplicate of #5. Please follow that issue for updates.

**Closed as not planned by fabiosangregorio** 2023-12-04 09:14 UTC
