### ISSUE TITLE
Automatically switches to day view

### ISSUE THREAD

**Issue by Jeroenvbeck** [fabiosangregorio/google-calendar-quick-duplicate#25] opened 2024-06-12 13:49 UTC
### Description
When duplicating an event the view automatically switches to day, but I only use week view so it would be nice if the view goes to what it previous was or if you could set your default view in the settings.

### Reproduction
Whenever duplicating an event it just goes to day view, shouldn't be hard to replicate

### Environment
Latest version on chrome webstore
On chrome, Windows 11, English language
I use Gcalplus which also changes a few things about google calander, don't know yet if this is the problem.

**Comment by fabiosangregorio** [comment] 2024-06-13 10:56
Duplicate of #5

**Closed as completed by fabiosangregorio** 2024-06-13 10:56 UTC
